<a href="https://colab.research.google.com/github/rvsvhy/Machine-Learning/blob/main/Machine_Learning_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
# 1) Count the no of vowels and consonants
a = str(input("Enter the string: ").upper())
print(a)
Q = list(a)

def isVowel(E):
    return E in ['A', 'E', 'I', 'O', 'U']

def count(array):
    countVowel = 0
    countConso = 0
    for i in array:
        if i.isalpha():  # Only count letters
            if isVowel(i):
                countVowel += 1
            else:
                countConso += 1
    return countVowel, countConso

answer = count(Q)
print("Vowels:", answer[0])
print("Consonants:", answer[1])


Enter the string: Skanda
SKANDA
Vowels: 2
Consonants: 4


In [28]:
import numpy as np

def define_matrices():
    A = np.array([[2, 3, 6], [4, 5, 1]])
    B = np.array([[1, 1, 3], [9, 7, 2], [5, 1, 7]])
    return A, B

def can_multiply(A, B):
    return A.shape[1] == B.shape[0]

def multiply_matrices(A, B):
    return np.dot(A, B)

def print_matrix(matrix, name):
    print(f"Matrix {name}:")
    print(matrix)
    print()

def main():
    A, B = define_matrices()
    print_matrix(A, "A")
    print_matrix(B, "B")

    if can_multiply(A, B):
        result = multiply_matrices(A, B)
        print_matrix(result, "A x B (Result)")
    else:
        print("Multiplication is not possible. Columns of A must equal rows of B.")

# Run the program
main()


Matrix A:
[[2 3 6]
 [4 5 1]]

Matrix B:
[[1 1 3]
 [9 7 2]
 [5 1 7]]

Matrix A x B (Result):
[[59 29 54]
 [54 40 29]]



In [19]:
# 3) Common elements in a list
def intersection(arr1, arr2):
  return [value for value in arr1 if value in arr2]

a1 = list(map(int, input("Enter the elements of the first array: ").split()))
a2 = list(map(int, input("Enter the elements of the second array: ").split()))

print(intersection(a1, a2))

Enter the elements of the first array: 2 3 7 8 4 1
Enter the elements of the second array: 3 9 4 0 6 0
[3, 4]


In [29]:
# 4) Transpose of a matrix
def Find_the_transpose():
  matrix = np.array([[2, 4, 6], [3, 9, 0], [4, 1, 1]])
  transpose = np.transpose(matrix)
  return transpose
answer = Find_the_transpose()
print(answer)

[[2 3 4]
 [4 9 1]
 [6 0 1]]


In [33]:
# 5) Mean median and mode of random numbers

import random
import numpy as np
from scipy import stats

def random_numbers(n, start, end):
    if end - start + 1 < n:
        raise ValueError("Range is too small for unique sampling.")
    return random.sample(range(start, end + 1), n)

def mean(data):
    return np.mean(data)

def mode(data):
    return stats.mode(data, keepdims=True)[0][0]

def median(data):
    return np.median(data)

data = random_numbers(100, 100, 200)
print("Random Numbers:", data)
print("Mean:", mean(data))
print("Mode:", mode(data))
print("Median:", median(data))


Random Numbers: [193, 124, 188, 121, 116, 153, 110, 137, 199, 181, 148, 191, 173, 195, 141, 135, 157, 140, 131, 133, 129, 192, 132, 105, 190, 178, 122, 118, 143, 158, 111, 104, 159, 164, 179, 123, 107, 162, 185, 106, 166, 142, 127, 109, 150, 155, 119, 120, 125, 197, 145, 130, 161, 103, 134, 187, 152, 194, 168, 167, 139, 156, 117, 108, 180, 165, 184, 170, 174, 102, 114, 169, 183, 151, 149, 147, 154, 100, 144, 146, 136, 182, 172, 189, 198, 163, 177, 138, 200, 196, 113, 115, 101, 128, 176, 112, 175, 126, 160, 186]
Mean: 149.79
Mode: 100
Median: 149.5
